version: '3.8'

services:
  web:
    build: .
    container_name: neksti_web
    restart: always
    ports:
      - "3001:3000" # O Nginx manda pra 3001, o Docker recebe e joga pra 3000 (Next.js)
    env_file:
      - .env.local  # Criado automaticamente pelo workflow do GitHub Actions