version: '3.8'

services:
  web:
    build: .
    container_name: neksti_web
    restart: always
    ports:
      - "3005:3000" # O Nginx precisará ser configurado para apontar para a 3005 (Docker roteará para a 3000 interna)
    env_file:
      - .env.local  # Criado automaticamente pelo workflow do GitHub Actions